# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'e-VMSS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for e-VMSS
    pod 'Firebase'
    pod 'Firebase/Auth'
    pod 'Firebase/Database'
    pod 'SVProgressHUD'
    pod 'Alamofire'
    pod 'SwiftyJSON'
    pod 'GoogleSignIn'
end
